version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_schema
    volumes:
      - db-data:/etc/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    image: app-hotel:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  db-data: