spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/hotel_schema
    username: postgres
    password: postgres
    hikari:
      schema: hotel_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotel_schema
      connection-timeout: 10000
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      uri: mongodb://root:root@mongodb:27017/statistics-database?authSource=admin

app:
  kafka:
    kafkaMessageTopic: statistics-topic
    kafkaMessageGroupId: statistics-event-group-id


  #logging:
  #  level:
  #    ROOT: DEBUG
